/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author USER
 */
public class HighScores extends javax.swing.JFrame {
    DB db;

    
    /**
     * Creates new form HighScores
     */
  
   
    public HighScores() {
        initComponents();
        db = new DB();
        db.selecAllData();
        nama1.setText(DB.nama[0]);
        nama2.setText(DB.nama[1]);
        nama3.setText(DB.nama[2]);
        nama4.setText(DB.nama[3]);
        nama5.setText(DB.nama[4]);
        skor1.setText(DB.skor[0]);
        skor2.setText(DB.skor[1]);
        skor3.setText(DB.skor[2]);
        skor4.setText(DB.skor[3]);
        skor5.setText(DB.skor[4]);
              
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nama1 = new javax.swing.JLabel();
        skor1 = new javax.swing.JLabel();
        skor2 = new javax.swing.JLabel();
        nama2 = new javax.swing.JLabel();
        nama3 = new javax.swing.JLabel();
        skor3 = new javax.swing.JLabel();
        nama4 = new javax.swing.JLabel();
        nama5 = new javax.swing.JLabel();
        skor4 = new javax.swing.JLabel();
        skor5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel1");

        jLabel6.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        nama1.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        nama1.setText("nama1");
        jPanel1.add(nama1);
        nama1.setBounds(250, 180, 267, 37);

        skor1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        skor1.setText("s1");
        jPanel1.add(skor1);
        skor1.setBounds(560, 180, 112, 37);

        skor2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        skor2.setText("s2");
        jPanel1.add(skor2);
        skor2.setBounds(560, 250, 112, 37);

        nama2.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        nama2.setText("nam2");
        jPanel1.add(nama2);
        nama2.setBounds(250, 250, 244, 37);

        nama3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        nama3.setText("nam3");
        jPanel1.add(nama3);
        nama3.setBounds(250, 330, 267, 33);

        skor3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        skor3.setText("s3");
        jPanel1.add(skor3);
        skor3.setBounds(560, 330, 99, 37);

        nama4.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        nama4.setText("na4");
        jPanel1.add(nama4);
        nama4.setBounds(250, 400, 267, 33);

        nama5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        nama5.setText("na5");
        jPanel1.add(nama5);
        nama5.setBounds(250, 470, 279, 33);

        skor4.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        skor4.setText("s4");
        jPanel1.add(skor4);
        skor4.setBounds(560, 400, 112, 37);

        skor5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        skor5.setText("s5");
        jPanel1.add(skor5);
        skor5.setBounds(560, 470, 135, 37);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/BackBtn.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(29, 574, 121, 97);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/highscorefix.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        area x = new area();
        x.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HighScores().setVisible(true);
              }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama2;
    private javax.swing.JLabel nama3;
    private javax.swing.JLabel nama4;
    private javax.swing.JLabel nama5;
    private javax.swing.JLabel skor1;
    private javax.swing.JLabel skor2;
    private javax.swing.JLabel skor3;
    private javax.swing.JLabel skor4;
    private javax.swing.JLabel skor5;
    // End of variables declaration//GEN-END:variables
}
